### ISSUE TITLE
Store Persian Text in Values

### ISSUE THREAD

**Issue by dimoibiehg** [Azure-Samples/azure-cosmos-db-graph-nodejs-getting-started#12]
The problem is when I wanna store text which is in Persian into the Cosmos Graph through a gremlin query in node js, It is failed:

     GremlinDriver.execute("g.V(id).out('includes')
                            .hasLabel('play')
                            .property('test', field_value)", 
                           { id: '123456', field_value: field_value })

If the the `field_value` is in Persian Language like ("تست") I will get `Gremlin Query Parse Error`.

**Comment by olivertowers** [comment]
Closing as this path is supported now.
