### ISSUE TITLE
SASL auth error trying to connect

### ISSUE THREAD

**Issue by chrisdias** [Azure-Samples/azure-cosmos-db-graph-nodejs-getting-started#13]
When running this app i get this error when trying to execute the "drop" command:

Access Denied: Gremlin websocket client failed to provide valid SASL authorization information that matches AuthorizedBackend configuration.

`config.js`:

``` javascript
config.endpoint = "******.graphs.azure.com";
config.primaryKey = "K.......=";
config.database = "graphdb"
config.collection = "graphcoll"
```

I copied the `primaryKey` straight from the Azure portal, under Keys -> Read-write Keys blade.

**Comment by olivertowers** [comment]
Can you verify the name of the `database` and `collection` you created graph database with? These will form the username that is supplied for the websocket connection and authentication will fail if it does not match the known database/collection pair.

**Comment by adityamakam** [comment]
Did anybody got solution for this?

**Comment by thomas-mindruptive** [comment]
The name of the collection seems to be case-sensitive. So for the quickstart sample app it would be "Persons", not "persons".

**Comment by johncastorina** [comment]
I am now getting this same error. I have triple checked all values for db, collection, primary key, endpoint for typos, casing, etc.

all values were copy pasted directly from my azure portal into my code.

Error output:
```
statusCode: 407,
  statusMessage: 'ActivityId: 994a2c61-067f-4a76-bcb1-aa8b1124a983\n' +
    'Gremlin server SASL authentication challenge.',
  statusAttributes: { 'x-ms-activity-id': '994a2c61-067f-4a76-bcb1-aa8b1124a983' }
```

Node version: v14.18.1

Library versions:
```gremlin: 3.5.1``` // have also tried earlier versions, including the exact version used in this repo.

**Comment by olivertowers** [comment]
@johncastorina  - not able to repro this. It looks like internally the client didn't handle the SASL auth handshake and instead through back the error to the caller, which shouldn't happen.
If you hadn't resolved this already, I'd recommend retrying with the latest sample using 3.4.13 driver.

**Comment by sthanase** [comment]
> I am now getting this same error. I have triple checked all values for db, collection, primary key, endpoint for typos, casing, etc.
> 
> all values were copy pasted directly from my azure portal into my code.
> 
> Error output:
> 
> ```
> statusCode: 407,
>   statusMessage: 'ActivityId: 994a2c61-067f-4a76-bcb1-aa8b1124a983\n' +
>     'Gremlin server SASL authentication challenge.',
>   statusAttributes: { 'x-ms-activity-id': '994a2c61-067f-4a76-bcb1-aa8b1124a983' }
> ```
> 
> Node version: v14.18.1
> 
> Library versions: `gremlin: 3.5.1` // have also tried earlier versions, including the exact version used in this repo.

Hello, were you able to resolve this problem, I am struggling with this for the past few days
