### ISSUE TITLE
ERROR: Partition key property must be provided

### ISSUE THREAD

**Issue by indigo-sam** [Azure-Samples/azure-cosmos-db-graph-nodejs-getting-started#20]
I created a graph db with Partition key value(it's required now). When I execute node app.js, it gives me error says:

`
Running Add Vertex1
Error:`
`
Gremlin Query Execution Error: Add Vertex: Modify Data: Partition key property must be provided for creating a vertex on a partitioned collection.`

NPM 5.6.0 
Node 8.9.4
Windows 10

**Comment by indigo-sam** [comment]
Nvm. Problem is solved.

**Comment by thomasjedstrom** [comment]
@indigo-sam how did you solve it?

**Comment by MartinWa** [comment]
Had the same error. Felt that @indigo-sam fitted well with [Wisdom of the Ancients](https://xkcd.com/979/)

Fond the answer in https://docs.microsoft.com/en-us/azure/cosmos-db/graph-partitioning

Either you create a fixed size graph or if you need an unlimited size you need to provide partition key to all calls.

**Comment by sebastiangug** [comment]
Ok. but how do you provide a partition key to all calls? where's the syntax? just googling 'gremlin nodejs partition key' find this thread as the only useful result.

**Comment by olivertowers** [comment]
A partition key is treated like property in Cosmos DB, so to include it when adding a vertex, you cane use `property(<partition_key_name>, <partition_key_value>)`

For example, if /name was the partition key path for the Graph, then you can add vertex with partition 'jane' as follows:

`g.addV('person').property('name', 'jane')`
