### ISSUE TITLE
Open / Close connection & performance

### ISSUE THREAD

**Issue by sittingbool** [Azure-Samples/azure-cosmos-db-graph-nodejs-getting-started#34]
Hi all, I noticed that if I open and close the connection on every request this is taking a bit long sometimes and with the serverless azure cosmo db it even hangs up completely sometimes. When I just keep the connection open for the runtime of my application, this is way more performant for single requests. Is this a valid implementation or how can this be solved? I am developing an API / Backend - Application with many requests that have to be performed in parallel.

**Comment by olivertowers** [comment]
Latest supported version of gremlin-javascript (`3.4.13` as of this comment) should maintain the connection over the lifetime of `client` instance and will be re-used for multiple requests. Note that gremlin-javascript does not support connection pooling, so you may need to consider how initializing more the one client instance in highly concurrent workloads.
