### ISSUE TITLE
New version of gremlin-javascript?

### ISSUE THREAD

**Issue by jinman** [Azure-Samples/azure-cosmos-db-graph-nodejs-getting-started#36]
Do we know any ETA on when with cosmos support new version of gremlin-javascript? 3.4.10 or 3.5.0 ? that includes elementMap() etc?. Its been 4 years without any update to library or the service. Please advice.

**Comment by olivertowers** [comment]
Sample is updated to reflect the latest client driver supported, however, this does not reflect what the server API surface area supports. Please see this the supported gremlin steps [here](https://docs.microsoft.com/en-us/azure/cosmos-db/graph/gremlin-support)
