### ISSUE TITLE
Can't terminate the connection

### ISSUE THREAD

**Issue by brianfoody** [Azure-Samples/azure-cosmos-db-graph-nodejs-getting-started#5]
There is no ability to end the websocket connection so it just hangs.

Can we add a close connection to gremlin-secure? I can't use this in an Azure Function until it's possible to terminate.

**Comment by brianfoody** [comment]
Have submitted a merge request to jbmusso/gremlin-javascript for this.

https://github.com/jbmusso/gremlin-javascript/pull/81

**Comment by LuisBosquez** [comment]
@brianfoody The official tinkerpop driver is now hosted here: https://github.com/apache/tinkerpop/tree/master/gremlin-javascript
