### ISSUE TITLE
Wildcard Vertex Property Searching

### ISSUE THREAD

**Issue by brianfoody** [Azure-Samples/azure-cosmos-db-graph-nodejs-getting-started#6]
I am trying to migrate from AWS Titan to Azure Cosmos and I am 90% there with making the switch. The only blocker I have is that there appears to be support for wildcard search on properties.

Consider this query;

g.V().has("Category",textContains("Shoes"))

It appears textContains is not supported in Cosmos as I get the below error. Will this be provided in future or should I plan for never being able to do wildcard text searching?

Error
(1,91): error CS0103: The name `textContains' does not exist in the current context

**Comment by LuisBosquez** [comment]
Hello @brianfoody,

There isn't string matching support in Cosmos DB just yet. This is an item that we have added to this semester's work. 

Thanks,
Luis
